kotlin.mpp.androidSourceSetLayoutVersion=2
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
org.jetbrains.compose.experimental.uikit.enabled=true
android.suppressUnsupportedCompileSdk=35
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
android.nonTransitiveRClass=true
kotlin.mpp.enableCInteropCommonization=true

# Compose compiler settings
android.enableComposeCompiler=true
kotlin.compiler.execution.strategy=in-process
