source 'https://cdn.cocoapods.org'
project 'iosApp.xcodeproj'

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-18'
  pod 'KMPNativeCoroutinesCore', '1.0.0-ALPHA-18'
end 