name: iosApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "14.0"
  minimumXcodeGenVersion: "2.10.0"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.iosApp
        DEVELOPMENT_TEAM: ""
        INFOPLIST_FILE: iosApp/Info.plist
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
    info:
      path: iosApp/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false 